In [3]:
import numpy as np

from gmx2qmmm.generators.pcf import PCFGeneratorShift

## Test system

In [4]:
input_field = np.array(
    [
        [47.830000000000005, 85.61999999999999, 31.12, 0.2943],
        [47.699999999999996, 84.87, 30.470000000000002, 0.1642],
        [47.199999999999996, 86.37, 30.9, 0.1642],
        [48.769999999999996, 85.95, 31.06, 0.1642],
        [47.56999999999999, 85.15, 32.47, -0.01],
        [48.2, 84.39999999999999, 32.67, 0.0895],
        [46.63, 84.81, 32.5, 0.0895],
        [47.76, 86.27000000000001, 33.47, 0.6163],
        [46.95, 86.44, 34.37, -0.5722],
        [48.86, 87.01, 33.34, -0.3821],
        [49.519999999999996, 86.78, 32.62, 0.2681],
        [49.14, 88.14999999999999, 34.21, -0.2722],
        [49.290000000000006, 87.77, 35.129999999999995, 0.1304],
        [50.38, 88.9, 33.76, 0.1123],
        [50.57000000000001, 89.64, 34.39, 0.0813],
        [51.16, 88.27, 33.74, 0.0813],
        [50.18, 89.42, 32.5, -0.6514],
        [50.949999999999996, 89.89000000000001, 32.22, 0.4474],
        [47.95, 89.09, 34.22, 0.8113],
        [47.699999999999996, 89.58, 33.38, -0.8132],
        [47.29, 89.26, 35.25, -0.8132],
    ]
)

charge = 1
qm_atoms = [0, 1, 2, 3, 4, 5, 6]
m1_atoms = [7]
m2_atoms = [[8, 9]]

In [5]:
pcf = PCFGeneratorShift(input_field=input_field, qm_atoms=qm_atoms, m1_atoms=m1_atoms, m2_atoms=m2_atoms)

In [8]:
pcf.correction_indices

[21, 22, 23, 24]

## Random data

In [ ]:
input_field = np.random.uniform(size=(10, 4))
qm_atoms = [0, 1, 2, 3]
m1_atoms = [4, 7]
m2_atoms = [[5, 6], [8, 9]]

In [ ]:
pcf = PCFGeneratorShift(input_field=input_field, qm_atoms=qm_atoms, m1_atoms=m1_atoms, m2_atoms=m2_atoms)

In [ ]:
pcf.input_field

array([[0.7480558 , 0.22583349, 0.23633396, 0.29362106],
       [0.49372903, 0.77125704, 0.6281093 , 0.18884276],
       [0.28014224, 0.96773194, 0.37610755, 0.6602132 ],
       [0.46438422, 0.4365693 , 0.31422542, 0.66338811],
       [0.73519466, 0.65431692, 0.6941965 , 0.8144084 ],
       [0.12810454, 0.55299016, 0.98052907, 0.94133655],
       [0.41605744, 0.91339081, 0.24822891, 0.70938154],
       [0.45435864, 0.54762049, 0.21968306, 0.34041307],
       [0.41981964, 0.16811514, 0.36083309, 0.36001812],
       [0.53345872, 0.99778626, 0.91303573, 0.66675948]])

In [ ]:
pcf.generate()

NameError: name 'n' is not defined

In [6]:
pcf.target_field_vector_

AttributeError: 'PCFGeneratorShift' object has no attribute 'target_field_vector_'

In [6]:
pcf._shift_qm_charges_to_m1()

In [7]:
pcf._output_field

array([[0.78321961, 0.54803495, 0.97500069, 0.        ],
       [0.23680521, 0.43344409, 0.4403934 , 0.        ],
       [0.1332237 , 0.73058563, 0.63294622, 0.        ],
       [0.46860325, 0.75267894, 0.79820656, 0.        ],
       [0.74594652, 0.92653993, 0.18527262, 2.10422147],
       [0.87325337, 0.63419564, 0.45184578, 0.39577025],
       [0.53025707, 0.23626472, 0.612022  , 0.62207614],
       [0.04444482, 0.08775846, 0.76428727, 1.84970213],
       [0.48909725, 0.05866977, 0.7677824 , 0.68481029],
       [0.16334438, 0.34113163, 0.83278972, 0.66157212]])

In [9]:
pcf._shift_m1_charges_to_m2()

array([ 0.1947075 , -1.29751909, -4.04079521])

In [17]:
a = np.array([1, 2, 4, 5, 7, 9, 8, 9])
b = [1, 3, 7]
a[b] += 1
print(a)

c = a[b]
c += 1
print(a)

[ 1  3  4  6  7  9  8 10]
[ 1  3  4  6  7  9  8 10]


In [19]:
np.sign(1)

np.int64(1)

In [25]:
0.5 - (0.5 / (2.0 * 10 + 1.0))

0.47619047619047616

In [3]:
0.1944 * (0.023333333333 / 0.023333333333)

0.1944