In [1]:
import numpy as np

from gmx2qmmm.generators.pcf import PCFGeneratorShift

## Test system

In [2]:
input_field = np.array(
    [
        [47.830000000000005, 85.61999999999999, 31.12, 0.2943],
        [47.699999999999996, 84.87, 30.470000000000002, 0.1642],
        [47.199999999999996, 86.37, 30.9, 0.1642],
        [48.769999999999996, 85.95, 31.06, 0.1642],
        [47.56999999999999, 85.15, 32.47, -0.01],
        [48.2, 84.39999999999999, 32.67, 0.0895],
        [46.63, 84.81, 32.5, 0.0895],
        [47.76, 86.27000000000001, 33.47, 0.6163],
        [46.95, 86.44, 34.37, -0.5722],
        [48.86, 87.01, 33.34, -0.3821],
        [49.519999999999996, 86.78, 32.62, 0.2681],
        [49.14, 88.14999999999999, 34.21, -0.2722],
        [49.290000000000006, 87.77, 35.129999999999995, 0.1304],
        [50.38, 88.9, 33.76, 0.1123],
        [50.57000000000001, 89.64, 34.39, 0.0813],
        [51.16, 88.27, 33.74, 0.0813],
        [50.18, 89.42, 32.5, -0.6514],
        [50.949999999999996, 89.89000000000001, 32.22, 0.4474],
        [47.95, 89.09, 34.22, 0.8113],
        [47.699999999999996, 89.58, 33.38, -0.8132],
        [47.29, 89.26, 35.25, -0.8132],
    ]
)

charge = 1
qm_atoms = [0, 1, 2, 3, 4, 5, 6]
m1_atoms = [7]
m2_atoms = [[8, 9]]

In [3]:
pcf = PCFGeneratorShift(input_field=input_field, qm_atoms=qm_atoms, m1_atoms=m1_atoms, m2_atoms=m2_atoms)

In [4]:
pcf.correction_indices

[21, 22, 23, 24]

In [5]:
pcf.generate()

array([[ 4.78300000e+01,  8.56200000e+01,  3.11200000e+01,
         0.00000000e+00],
       [ 4.77000000e+01,  8.48700000e+01,  3.04700000e+01,
         0.00000000e+00],
       [ 4.72000000e+01,  8.63700000e+01,  3.09000000e+01,
         0.00000000e+00],
       [ 4.87700000e+01,  8.59500000e+01,  3.10600000e+01,
         0.00000000e+00],
       [ 4.75700000e+01,  8.51500000e+01,  3.24700000e+01,
         0.00000000e+00],
       [ 4.82000000e+01,  8.44000000e+01,  3.26700000e+01,
         0.00000000e+00],
       [ 4.66300000e+01,  8.48100000e+01,  3.25000000e+01,
         0.00000000e+00],
       [ 4.77600000e+01,  8.62700000e+01,  3.34700000e+01,
         0.00000000e+00],
       [ 4.69500000e+01,  8.64400000e+01,  3.43700000e+01,
         2.13900000e-01],
       [ 4.88600000e+01,  8.70100000e+01,  3.33400000e+01,
         4.04000000e-01],
       [ 4.95200000e+01,  8.67800000e+01,  3.26200000e+01,
         2.68100000e-01],
       [ 4.91400000e+01,  8.81500000e+01,  3.42100000e+01,
      

## Random data

In [6]:
input_field = np.random.uniform(size=(10, 4))
qm_atoms = [0, 1, 2, 3]
m1_atoms = [4, 7]
m2_atoms = [[5, 6], [8, 9]]

In [7]:
pcf = PCFGeneratorShift(input_field=input_field, qm_atoms=qm_atoms, m1_atoms=m1_atoms, m2_atoms=m2_atoms)

In [8]:
pcf.input_field

array([[0.19828555, 0.63771071, 0.65422047, 0.68142424],
       [0.38146225, 0.094682  , 0.91893589, 0.32338422],
       [0.11245571, 0.00261775, 0.25650164, 0.57441367],
       [0.9912145 , 0.76204677, 0.21361397, 0.55733465],
       [0.52441431, 0.15110439, 0.5702621 , 0.23819253],
       [0.69065036, 0.08111389, 0.46327565, 0.5601343 ],
       [0.99350707, 0.29901051, 0.59769908, 0.03376604],
       [0.10815608, 0.95282773, 0.31426093, 0.54554391],
       [0.66856844, 0.44149251, 0.22190145, 0.02516497],
       [0.65165558, 0.3392716 , 0.66434979, 0.23403569]])

In [9]:
pcf.generate()

array([[ 0.19828555,  0.63771071,  0.65422047,  0.        ],
       [ 0.38146225,  0.094682  ,  0.91893589,  0.        ],
       [ 0.11245571,  0.00261775,  0.25650164,  0.        ],
       [ 0.9912145 ,  0.76204677,  0.21361397,  0.        ],
       [ 0.52441431,  0.15110439,  0.5702621 ,  0.        ],
       [ 0.69065036,  0.08111389,  0.46327565,  1.21336976],
       [ 0.99350707,  0.29901051,  0.59769908,  0.6870015 ],
       [ 0.10815608,  0.95282773,  0.31426093,  0.        ],
       [ 0.66856844,  0.44149251,  0.22190145,  0.83207612],
       [ 0.65165558,  0.3392716 ,  0.66434979,  1.04094684],
       [ 0.2356482 ,  0.27268383,  0.75610665,  0.26722533],
       [ 1.14565252, -0.11045605,  0.17044465, -0.26722533],
       [ 0.54424233,  0.15735622,  0.57142183,  0.24274542],
       [ 1.44277182,  0.4406648 ,  0.62397634, -0.24274542],
       [ 0.10623892,  0.954577  ,  0.31457689,  0.30266014],
       [ 1.23089796, -0.07159199,  0.12922601, -0.30266014],
       [-0.03557435,  1.

In [10]:
pcf.target_field_vector_

array([-1.4773672 ,  2.56858645, -0.95818469])